// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_Work_2.Models;

namespace Project_Work_2.Migrations.jb
{
    [DbContext(typeof(JobDbContext))]
    [Migration("20201013143743_InitialCreatejb")]
    partial class InitialCreatejb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project_Work_2.Models.JobAdvertisement", b =>
                {
                    b.Property<int>("JobAdvertisementId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("JobTypeName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("OnlineJobSiteId");

                    b.Property<string>("Responsibility")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("JobAdvertisementId");

                    b.HasIndex("OnlineJobSiteId");

                    b.ToTable("JobAdvertisements");
                });

            modelBuilder.Entity("Project_Work_2.Models.JobApplicant", b =>
                {
                    b.Property<int>("JobApplicantId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("JobAdvertisementId");

                    b.Property<string>("JobApplicantName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("JobApplicantId");

                    b.HasIndex("JobAdvertisementId");

                    b.ToTable("JobApplicants");
                });

            modelBuilder.Entity("Project_Work_2.Models.OnlineJobSite", b =>
                {
                    b.Property<int>("OnlineJobSiteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OnlineJobSiteName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("StartedJourney")
                        .HasColumnType("date");

                    b.Property<bool>("Web");

                    b.HasKey("OnlineJobSiteId");

                    b.ToTable("OnlineJobSites");
                });

            modelBuilder.Entity("Project_Work_2.Models.JobAdvertisement", b =>
                {
                    b.HasOne("Project_Work_2.Models.OnlineJobSite", "OnlineJobSite")
                        .WithMany("JobAdvertisements")
                        .HasForeignKey("OnlineJobSiteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Project_Work_2.Models.JobApplicant", b =>
                {
                    b.HasOne("Project_Work_2.Models.JobAdvertisement", "JobAdvertisement")
                        .WithMany("JobApplicants")
                        .HasForeignKey("JobAdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
